### ISSUE TITLE
Cursor position only works to first tag on return to WYSIWYG

### ISSUE THREAD

**Issue by kpaxman** [w8tcha/CKEditor-TextSelection-Plugin#19]
This sounds like https://github.com/w8tcha/CKEditor-TextSelection-Plugin/issues/4#issuecomment-87046956 but I don't think it's related to CodeMirror, as it happens even when I disable the CodeMirror plugin.

I am not experiencing this on the demo page, but I am when I enable this extension inside our Drupal setup.

Steps to demo (in Drupal):

In the WYSIWYG, create 2 paragraphs.

Position the cursor at the end of the 2nd paragraph. Switch to source view, and the cursor remains at the end of the 2nd one. Switch back to WYSIWYG, and the cursor moves to the end of the first one.

Position the cursor anywhere in the first paragraph. Switch back and forth from source view, and the cursor remains at the correct position.

In WYSIWYG, make a word in the first paragraph bold. Position the cursor at the end of the 2nd paragraph. Switch to source view, and the cursor remains in the correct position. Switch back to WYSIWYG, and the cursor moves to the end of the bold word from the first paragraph.

**Comment by kpaxman** [comment]
I haven't done extensive testing on this yet, but at first glance I lose my cursor entirely, and as I switch back and forth I get additional  comments appearing in source view.

**Comment by w8tcha** [comment]
sorry that was my spell checker, now it should work

**Comment by kpaxman** [comment]
That seems to have done it - at least it seems to be working with a new quick glance. :)

**Comment by heddn** [comment]
This is still an issue for me with code mirror and the latest commit from text selection ( Git commit hash: c439c4e09a3cf81084317dc33e53deb21d8fb9cc )
