### ISSUE TITLE
add source dialogue compatibility

### ISSUE THREAD

**Issue by sirtet** [w8tcha/CKEditor-TextSelection-Plugin#2]
seems like the source dialogue needs special treating.

**Comment by bumpyflea** [comment]
Hi,
Do you have any plans on making this plugin compatible with the source dialog view?

**Comment by w8tcha** [comment]
no at the moment not, i not have enough time for that.

**Comment by w8tcha** [comment]
This feature is now implemented in the CodeMirror Plugin v1.18.6  But only when opening the source Dialog with CodeMirror. When the dialog is closed it looses the focus and the text selection can't be saved
