### ISSUE TITLE
Could this work with other source code plugins?

### ISSUE THREAD

**Issue by henweigh** [w8tcha/CKEditor-TextSelection-Plugin#20]
Could the same technique be used with a similar source code plugin that uses something other than CodeMirror?  For example, the following plugin replaces the default source editor with Ace editor (it's still under development):

http://ckeditor.com/forums/CKEditor/ACE-Editor-Plugin-for-CKEditor-Source-View-Replacement-First-Draft

**Comment by w8tcha** [comment]
Technically yes, but it depends if such editor provide a similar API as CodeMirror. And that plugin for ACE is not really usably right now, and it is even in development?

**Comment by henweigh** [comment]
Here's the latest version of the plugin. I've been using it for awhile now and seems to work in most major browsers I've tested it in.  It's my first CKEditor plugin and my first time using GitHub so hopefully this will work:

https://github.com/henweigh/CKEditor-ACEEditor-Plugin
