### ISSUE TITLE
If cursor is in the <head> section of a FullPage document, extra code is added

### ISSUE THREAD

**Issue by larsinsd** [w8tcha/CKEditor-TextSelection-Plugin#22]
If you have a CKEditor document set to fullPage: true, and place your cursor within the <head> section of the HTML document, it will add extra HTML comments tags.

Example:

This has occurred for all versions of CKEditor.  The test configuration of the editor includes these plugins:

about,a11yhelp,basicstyles,blockquote,clipboard,contextmenu,resize,toolbar,elementspath,enterkey,entities,filebrowser,floatingspace,format,horizontalrule,htmlwriter,wysiwygarea,image,indentlist,link,list,magicline,maximize,pastetext,pastefromword,removeformat,showborders,sourcearea,specialchar,scayt,stylescombo,tab,table,tabletools,undo,wsc,dialog,dialogui,fakeobjects,floatpanel,indent,listblock,menu,menubutton,popup,panel,richcombo,button,font,find,selectall,justify,colorbutton,showblocks,indentblock,colordialog,div,forms,iframe,iframedialog,autogrow,tableresize,stylesheetparser,bidi,dialogadvtab,panelbutton,print,docprops

**Comment by mercurylmy** [comment]
This problem happen when set "config.fullPage = true;". Switching WYSIWYG to Source will keep text-selection, but Source to WYSIWYG won't. Waiting for a solution.

**Comment by larsinsd** [comment]
I'm hoping someone fixes this.  This is a great plugin (in theory).  Unfortunately, this has been an open issue for almost a year, and no one seems to care enough to fix it.

**Comment by w8tcha** [comment]
I tried to fix it but this is a really complex problem. And there is no solution to the problem.

**Comment by larsinsd** [comment]
That is really unfortunate.  If you can't fix this, given that it breaks the HTML, you should take down this plugin, or at least put a big warning to all users that it doesn't work in fullPage:true mode.

**Comment by w8tcha** [comment]
i commited a change the plugin is now disabled when using fullPage

**Comment by mercurylmy** [comment]
@w8tcha Maybe you shouldn’t add comments to \<head\>. Use some variables to store them. I really hope this plugin works in fullPage mode. Thanks.

**Comment by sirtet** [comment]
@w8tcha
> I tried to fix it but this is a really complex problem. And there is no solution to the problem.

Maybe you could tell some details about the problem, and why it can't be solved?
Also, i would leave this ticket open, so it might get more attention, and maybe someday a solution is found.
Or better open a new issue?

**Comment by w8tcha** [comment]
The problem is how the plugin works is it injects comment tags inside the html to save the cursor positions. At the moment this is the only solution on how the plugin works, buts this causes some troubles. Until there is a different solution, this can not be fixed.
