### ISSUE TITLE
Selected text is removed in IE10 and IE11

### ISSUE THREAD

**Issue by mdenburger** [w8tcha/CKEditor-TextSelection-Plugin#23]
In IE10 and IE11, selected text is removed instead of highlighted.

Steps to reproduce:
1. use CKEditor 4.4.8 and the latest codemirror and textselection plugins
2. open the samples/replacebycode.html example (including the codemirror and textselection plugins) in IE10 or IE11
3. select some text in the editing area
4. click 'Source' to switch to source mode

Expected: the selected text is selected
Actual: the selected text is deleted

**Comment by w8tcha** [comment]
i guess that issue is resolved i can not reproduce it with IE11 and the latest versions of the editor & plugins
