### ISSUE TITLE
Content lost when clicking undo after switching from WYSIWYG to SOURCE and back to WYSIWYG

### ISSUE THREAD

**Issue by abogaart** [w8tcha/CKEditor-TextSelection-Plugin#25]
Hi!

Recently one of our editors found an issue where a piece of content is out when 'undo' is clicked after switching from WYSIWYG to SOURCE and back to WYSIWYG.

The full reproduction path is as follows:
- start with a clean CKEditor instance (text-selection and codemirror plugins enabled)
- enter a line of text
- switch to <source>
- switch back to <wysiwyg>
- enter a second line of text and make a couple of characters bold
- press undo

Expected: the last action would be undone, i.e. making a few characters bold.
Observed: all changes that were made after switching back to <wysiwyg> are lost.

I think this issue is caused because the function 'createBookmark' is called twice when switching from <source> to <wysiwyg> which in turn causes the lockmanager to never become unlocked (as the locked.level value stays above 0). 

I found a workaround which is to simply call `editor.undoManager.unlock() ` in the last line of createBookmark, but that might not play well with previous fixes done in this area?

**Comment by w8tcha** [comment]
Ok i fixed this in the codemirror plugin https://github.com/w8tcha/CKEditor-CodeMirror-Plugin/commit/7b36076ce27a83c6087781b998e96f657813c073

**Comment by abogaart** [comment]
Works like a charm, thanks a lot!
