### ISSUE TITLE
cursor misplaced returning from sourcodeview

### ISSUE THREAD

**Issue by arbyter1** [w8tcha/CKEditor-TextSelection-Plugin#26]
hi
i tried out your marvelous plugin. Works like a charm on your demo site.
I implemented it in my project and realized, that the cursor is misplaced changing from source code to WYSIWYG view.
I replaced the version 1.04 with the source of 1.03 (grabbing it from your demo project).  
--- no more misplacing. 
What would be the benefit of version 1.04?
Thank you anyway for your work

**Comment by arbyter1** [comment]
After playing around with this plugin i had to realize, that in version 1.03 following issue exists:
When the cursor is placed in a <td colspan=3> , switching back to wysiwyg inserts another td to the source.
I tried it in your demo page.
Version 1.04 does not have  this behavior but  still the missplace cursror switching back to wysiwyg.

**Comment by arbyter1** [comment]
After playing around with this plugin i had to realize, that in version 1.03 following issue exists:
When the cursor is placed in a , switching back to wysiwyg inserts another td to the source.
I tried it in your demo page.
Version 1.04 does not have this behavior but still the missplace cursror switching back to wysiwyg.

**Comment by w8tcha** [comment]
can you describe the exact steps to reproduce the problem`? or provide the html you use where there problem exist? i tried with an a tag as you described but the cursor is correct

**Comment by arbyter1** [comment]
i found now out how to reproduce the problem: 
when in sourcemodus the cursor is in the <table  tag, then it inserts another tbody tag, 
when the coursor is  in the <tbody tag, it inserts another <tr etc.

**Comment by w8tcha** [comment]
This is the same issue as #27 and #28 this is one of the limitations of the plugin. Unless i found a better solution to save the position this issue will never be fixed
