### ISSUE TITLE
Switching from Source to WYSIWIG and back duplicates TABLE/TR/TD 

### ISSUE THREAD

**Issue by tomsuchy** [w8tcha/CKEditor-TextSelection-Plugin#27]
Hi there,

Found a bug where placing the cursor inside a &lt;table&gt; tag in Source view, and  then switching to WYSIWYG and back to Source, duplicates content.

I tried this at the demo page: http://w8tcha.github.io/CKEditor-TextSelection-Plugin/demoCodeMirror.html

Enter the following in Source view:

`<table><tr><td>Hi</td></tr></table>`

Place the mouse inside the 'table' tag somewhere, go to WYSIWYG, and then back to Source, you'll see it has added another row.

Recreated on Linux Chrome 59 and Mac Chrome;

Please let me know if you need additional info.

Thanks!
-Tom

**Comment by w8tcha** [comment]
this is one of the limitations of the plugin. Unless i found a better solution to save the position this issue will never be fixed

**Comment by w8tcha** [comment]
i'm testing a new solution

https://github.com/w8tcha/CKEditor-TextSelection-Plugin/releases/tag/v1.07
