### ISSUE TITLE
Storing content in browser local storage does not work properly / sporadically loses changes without local storage

### ISSUE THREAD

**Issue by roadlittledawn** [w8tcha/CKEditor-TextSelection-Plugin#29]
Love the plugin when it works, but found a couple issues when implementing this on our Drupal site. 

The HTML string wasn't always loaded into browser local storage and when switching from WYSIWYG mode to Source, it would error out and disable Source view mode. This happened sporadically and could not discern a pattern.

I removed the code that deals with local storage and it worked more consistently; however, it had more issues. It sporadically discards any changes made in either WYSIWYG or Source mode when switching between the two.

**Comment by w8tcha** [comment]
What errors are you getting? and which browser did you use?

**Comment by roadlittledawn** [comment]
i of course cannot reproduce the local storage error right now, but i believe it was a cannot read length of null at line 342 which is:

    var diff = content.length - savedContent.length;

the local storage error occurred in Chrome (Version 63.0.3239.84 (64-bit)) and Firefox 57.0 (64-bit). 

i can still reproduce losing data when switching between Source and WYSIWYG modes. that also happens in those version of Chrome and Firefox. right now, looks like it loses data when switching from WYSIWYG to Source mode. it correctly saves content when switching from Source to WYSIWYG. if i remove the local storage code, it works most of the time. occasionally, users have noticed missing content when switching between Source and WYSIWYG.

are there version requirements to use this? we are on codemirror plugin 1.17.4 and sourcearea plugin 4.5.11. our Drupal ckeditor module version is 1.17 (the ckeditor version our drupal module is running is 4.5.6).

**Comment by roadlittledawn** [comment]
also, FWIW: with the local storage code removed, i think the intermittent missing data issue may be related to the browsers caching the old version of the plugin's javascript. i changed the timestamp token in this line of code in **ckeditor/ckeditor/ckeditor.js** file (drupal module path) to force browser to get latest file and it seems to work in local and dev environments.

**Comment by w8tcha** [comment]
i added some checks that should avoid the issues with the localstorage
