### ISSUE TITLE
Dropping selection when switching to WYSIWYG if the selection starts or ends with the HTML element

### ISSUE THREAD

**Issue by dryoma** [w8tcha/CKEditor-TextSelection-Plugin#32]
Hey again!

Encountering the plugin resetting text selection in certain cases. Specifically, if the selection start or end corresponds to the start or the end of an HTML element _and_ the selection does not expand beyond that element; or if the selection wrapps several elements contents entirely. It happens if we either select text in wysiwyg then switch to source then back to wysiwyg, or if we select something in source and go to wysiwyg. For example (selections are marked with `[]`):

- `<p>This [is tex]t.</p>` - not dropped.
- `<p>This [is text.]</p>` - dropped.
- `<p>[This ]is text.</p>` - dropped.
- `<p>Me is king-[kong.</p><p>This ]is text.</p>` - not dropped.
- `<p>[Me is king-kong.</p><p>This ]is text.</p>` - not dropped.
- `<p>[Me is king-kong.</p><p>This is text.]</p>` - dropped.
- `<p>[Me is king-kong.</p><p>This is <i>text.</i>]</p>` - dropped.

Here is a screencast:

![selection](https://user-images.githubusercontent.com/11942776/42550445-5401416e-8504-11e8-9db6-2993f26ff96b.gif)

**Comment by w8tcha** [comment]
Sorry for my late answer. Atleast with chrome i can not reproduce the issue. Which browser did you use?

**Comment by dryoma** [comment]
Hey @w8tcha 
I am seeing this in Firefox (the latest version), and in older Chromium (47). Just now tried the newest CKEditor and the lates commit of `textselection` - the issue is still there.
