### ISSUE TITLE
CKEditor 5 upgrade

### ISSUE THREAD

**Issue by carsoncho** [w8tcha/CKEditor-TextSelection-Plugin#36]
I'd like to use this plugin for CKEditor 5, but see there's no released version supporting 5. Will this plugin be compatible with CKEditor5? Are there API changes that need to be implemented that currently prevent this plugin from being compatible with CKEditor 5?

**Comment by w8tcha** [comment]
The problem is that ckeditor 5 is not an upgrade. It's a completely different editor, which was build up from the ground.

This would require to rewrite the entire plugin. Unfortunately I don't have the free time for this. 

So at this point there will be no plugin for ckeditor 5.
