### ISSUE TITLE
TextSelection doesn't work in SourceDialog with CodeMirror

### ISSUE THREAD

**Issue by sunwayru** [w8tcha/CKEditor-TextSelection-Plugin#37]
Hello! Why it doesn't work from
https://ckeditor.com/cke4/addon/textselection
with [CodeMirror (Source) Syntax Highlighting] (https://ckeditor.com/cke4/addon/codemirror)
Please fix the much needed plugin.

**Comment by w8tcha** [comment]
i updated the demo site to the latest version of the editor and plugins, and it works without issues.

You can see here.

http://w8tcha.github.io/CKEditor-TextSelection-Plugin/demoCodeMirror.html

**Comment by sunwayru** [comment]
Thanks for the reply! 
I use CKEditor4 in inline mode, therefore instead of [Source Editing Area](https://ckeditor.com/cke4/addon/sourcearea) I use  [Source Dialog](https://ckeditor.com/cke4/addon/sourcedialog), and TextSelection does not work.

**Comment by sunwayru** [comment]
var CKBUILDER_CONFIG = {
	skin: 'moono-lisa',
	preset: 'standard',
	ignore: [
		'.DS_Store',
		'.bender',
		'.editorconfig',
		'.gitattributes',
		'.gitignore',
		'.idea',
		'.jscsrc',
		'.jshintignore',
		'.jshintrc',
		'.mailmap',
		'.npm',
		'.nvmrc',
		'.travis.yml',
		'bender-err.log',
		'bender-out.log',
		'bender.ci.js',
		'bender.js',
		'dev',
		'gruntfile.js',
		'less',
		'node_modules',
		'package-lock.json',
		'package.json',
		'tests'
	],
	plugins : {
		'a11yhelp' : 1,
		'basicstyles' : 1,
		'blockquote' : 1,
		'clipboard' : 1,
		'codemirror' : 1,
		'colorbutton' : 1,
		'colordialog' : 1,
		'contextmenu' : 1,
		'copyformatting' : 1,
		'embed' : 1,
		'emoji' : 1,
		'entities' : 1,
		'filebrowser' : 1,
		'find' : 1,
		'floatingspace' : 1,
		'font' : 1,
		'format' : 1,
		'horizontalrule' : 1,
		'htmlwriter' : 1,
		'iframe' : 1,
		'image2' : 1,
		'indentblock' : 1,
		'indentlist' : 1,
		'justify' : 1,
		'link' : 1,
		'list' : 1,
		'liststyle' : 1,
		'magicline' : 1,
		'openlink' : 1,
		'pastetext' : 1,
		'removeformat' : 1,
		'resize' : 1,
		'selectall' : 1,
		'showblocks' : 1,
		'showborders' : 1,
		'sourcearea' : 1,
		'sourcedialog' : 1,
		'specialchar' : 1,
		'stylescombo' : 1,
		'tab' : 1,
		'table' : 1,
		'tableresize' : 1,
		'tableselection' : 1,
		'tabletools' : 1,
		'toolbar' : 1,
		'undo' : 1,
		'uploadfile' : 1,
		'uploadimage' : 1,
		'wysiwygarea' : 1
	},
	languages : {
		'en' : 1
	}
};

**Comment by w8tcha** [comment]
The plugin currently doesn't support the source dialog.

**Comment by w8tcha** [comment]
This feature is now implemented in the CodeMirror Plugin v1.18.6  But only when opening the source Dialog with CodeMirror. When the dialog is closed it looses the focus and the text selection can't be saved

**Comment by sunwayru** [comment]
Thanks for adding the opportunity! :) Very cool plugin!!!
Now it’s working with text, but there are bug, if editing area conents tables or widgets, textselection does not keep the position, but focuses in an incomprehensible place. You can check on simple content:

```
<div class="table-wrapper">
  <table border="1" cellpadding="1" cellspacing="1">
    <tbody>
      <tr>
        <td>&nbsp;
        </td>
        <td>&nbsp;
        </td>
      </tr>
      <tr>
        <td>&nbsp;
        </td>
        <td>&nbsp;
        </td>
      </tr>
    </tbody>
  </table>
</div>
<p>Lorem ipsum
</p>
```

**Comment by w8tcha** [comment]
atleast for me it works

**Comment by sunwayru** [comment]
no, the plugin does not correctly determine the position in the source code if the page content contains widgets

**Comment by sunwayru** [comment]
and the second bug: if you switch to the source code when the page is empty, plugin breaks the whole CKEditor
