### ISSUE TITLE
Plugin does not work with CodeMirror

### ISSUE THREAD

**Issue by nikkimk** [w8tcha/CKEditor-TextSelection-Plugin#4]
1. Downloaded ckeditor from http://ckeditor.com/builder with only codemirror and textselection as additional plugins.
2. Opened ckeditor/samples/divreplace.html
3. Selected text.
4. Got the following error: NS_ERROR_FAILURE:
   error source line ckeditor.js (390):...{for(var a=b.getRanges()[0].clone(),c,d,e=2;e&&(!(c=a.getEnclosedNode())||!(c.ty...
5. The selection was incorrect.

**Comment by skegel13** [comment]
I am still having the issue where the text selection works going into source mode but it loses it when going back to wysiwyg. It just goes back to the top of the document.

I am using the master branches from both the textselection and codemirror repositories as of 3/27/15 and version 4.4.6 of CKEditor.

**Comment by w8tcha** [comment]
Is that still an issue with the latest versions of the plugins? if yes pleas reopen
