### ISSUE TITLE
Empty paragraphs added when codesnippet plugin is active

### ISSUE THREAD

**Issue by mdenburger** [w8tcha/CKEditor-TextSelection-Plugin#9]
The textselection plugin adds empty paragraphs when switching from normal view to source view after a code snippet has been added. The fix for #5 only fixed the case when the editing area is empty.

Reproduction path:
  1. clone ckeditor 4.4.1
  2. add the textselection plugin
  3. enable the textselection and codesnippet plugin in samples/replacebycode.html
  (configuration: { extraPlugins: 'textselection,codesnippet' } )
  4. clear all text in the editor
  5. add a code snippet with the text 'foo'
  6. switch to source mode

Expected: the source is:

    <pre>
    <code>foo</code></pre>

Actual: the source is:

    <p>&nbsp;</p>

    <pre>
    <code>foo</code></pre>

    <p>&nbsp;</p>

    <p>&nbsp;</p>

**Comment by w8tcha** [comment]
issue should be fixed with latest version
